spring.application.name=BankingWebApplication1

spring.datasource.url=jdbc:postgresql://smartbank-db.cvkc6e8s0bhm.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Farheen1999
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.sendgrid.api-key=SG.I-3EZLU7SIykQdjnzjs2kg.Yi9mp9tT6XkaeyiC0Cyt4Ba3AuOZ7NXb8WkH0f2yvV8Copied!
spring.sendgrid.from-email=smartbankofficiale@gmail.com

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

