spring.application.name=BankingWebApplication1

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

# SendGrid
#sendgrid.api.key=${SENDGRID_API_KEY}
#spring.sendgrid.from-email=smartbankofficiale@gmail.com

app.mail.from=no-reply@smartbankofficial.online

spring.mail.host=email-smtp.eu-north-1.amazonaws.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.file.name=/home/ubuntu/BankingWebApplication1/logs/app.log
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG











