spring.application.name=BankingWebApplication1

spring.datasource.url=jdbc:postgresql://localhost:5432/bankingwebapplication
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=sam
spring.security.user.password=samir